services:
  - type: web
    name: SGDC_ASDO
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn tu_proyecto.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tu_proyecto.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nombre-de-tu-db
          property: connectionString

databases:
  - name: nombre-de-tu-db
    plan: free
    databaseName: tu_db
    user: tu_usuario